apps/cart/urls.py
from django.urls import path
from apps.cart.views import CartView, CartAddView


urlpatterns = [
    path('add', CartAddView.as_view(), name='add'), # 添加数据到购物车
    path('', CartView.as_view(), name='cart'),  # 购物车

]

apps/goods/urls.py
from django.urls import path, re_path
from apps.goods.views import IndexView, DetailView, ListView

urlpatterns = [
    path('index', IndexView.as_view(), name='index'),
    re_path('^goods/(?P<goods_id>\d+?)$', DetailView.as_view(), name='detail'),
    re_path('^list/(?P<type_id>\d+)/(?P<page>\d+)$', ListView.as_view(), name='list'),

]

apps/user/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required
from apps.user.views import RegisterView, ActiveView, LoginView, CenterInfoView, CenterOrderView, CenterSiteView, LogoutView

urlpatterns = [
    path('register', RegisterView.as_view(), name='register'),  # 用户注册
    re_path('^active/(?P<token>.*)$', ActiveView.as_view(), name='active'),  # 用户激活
    path('login', LoginView.as_view(), name='login'),  # 登录
    path('logout', LogoutView.as_view(), name='logout'),  # 退出
    path('',  CenterInfoView.as_view(), name='user'),  # 用户信息中心
    path('order', CenterOrderView.as_view(), name='order'),  # 用户中心订单
    path('address', CenterSiteView.as_view(), name='address'),  # 用户中心订单

]


dailyfresh/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),  # 富文本编辑器
    path('search/', include('haystack.urls')),
    path('order/', include(('apps.order.urls', 'order'), namespace='order')),  # 订单
    path('user/', include(('apps.user.urls', 'user'), namespace='user')),  # 用户信息
    path('cart/', include(('apps.cart.urls', 'cart'), namespace='cart')),  # 购物车
    path('', include(('apps.goods.urls', 'goods'), namespace='goods')),  # 商品

]

apps/cart/models.py
from django.db import models

# Create your models here.

apps/cart/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http.response import JsonResponse
from apps.goods.models import GoodsSKU
from django_redis import get_redis_connection
from utils.mixin import LoginRequiredMixin


# Create your views here.


class CartView(LoginRequiredMixin, View):

    def get(self, request):
        '''购物车'''
        # 用户
        user = request.user
        # 获取用户购物车商品的信息
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        cart_dict = conn.hgetall(cart_key)

        skus = list()
        # 总数目
        total_count = 0
        # 总价格
        total_amount = 0
        # 商品信息
        for sku_id, count in cart_dict.items():
            # 根据id获取信息
            sku = GoodsSKU.objects.get(id=sku_id)
            amount = sku.price * int(count)
            # 小记
            sku.amount = amount
            # 数量
            sku.count = int(count)

            total_amount += amount
            total_count += int(count)
            # 添加
            skus.append(sku)

        context = {
            'total_count': total_count,
            'total_amount': total_amount,
            'skus': skus,
        }

        return render(request, 'cart.html', context)


class CartAddView(View):
    '''添加购物车'''

    def post(self, request):
        '''购物车记录添加'''
        # 接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')
        user = request.user

        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

        # 检验商品数量
        try:
            count = int(count)
            # if count <= 0:
            #     raise Exception('商品数量不能必须大于0')
        except Exception as e:
            return JsonResponse({'res': 2, 'errmsg': '商品数量出错'})

        # 检验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 业务处理 ；添加购物车
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        # 不存在，返回none
        cart_count = conn.hget(cart_key, sku_id)
        if cart_count:
            count += int(cart_count)
        # 校验商品的库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})

        # 设置key对应的值
        conn.hset(cart_key, sku_id, count)

        # 计算用户购物车中商品到条目
        total_count = conn.hlen(cart_key)

        # 返回应答
        return JsonResponse({'res': 5, 'msg': '添加成功', 'total_count': total_count})

templates/base.html
{#  首页，  登录， 注册 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load static %}
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 页面标题块 #}
    <title>{% block title %}{% endblock title %}</title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {# 网页顶部引用文件块 #}
    {% block topfiles %} {% endblock topfiles %}
</head>
<body>
{# 网页顶部欢迎信息块 #}
{% block header_con %}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到天天生鲜!</div>
            <div class="fr">
                {% if user.is_authenticated %}
                    <div class="login_btn fl">
                        欢迎您：<em>{{ user.username }}</em>
                        <span>|</span>
                        <a href="{% url 'user:logout' %}">退出 </a>
                    </div>
                {% else %}
                    <div class="login_btn fl">
                        <a href="{% url 'user:login' %}">登录</a>
                        <span>|</span>
                        <a href="{% url 'user:register' %}">注册</a>
                    </div>
                {% endif %}
                <div class="user_link fl">
                    <span>|</span>
                    <a href="{% url 'user:user' %}">用户中心</a>
                    <span>|</span>
                    <a href="{% url 'cart:cart' %}">我的购物车</a>
                    <span>|</span>
                    <a href="{% url 'user:order' %}">我的订单</a>
                </div>
            </div>
        </div>
    </div>
{% endblock header_con %}

{# 顶部搜索块 #}
{% block search_bar %}
    <div class="search_bar clearfix">
        <a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
        <div class="search_con fl">
            <form method="get" action="/search">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
        </div>
        <div class="guest_cart fr">
            <a href="/cart" class="cart_name fl">我的购物车</a>
            <div class="goods_count fl" id="show_count">{% block cartCount %}0{% endblock cartCount %}</div>
        </div>
    </div>
{% endblock search_bar %}

<body>
{# 主体 #}
{% block body %}{% endblock body %}
</body>

<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>
</div>

{# 网页底部html元素块 #}
{% block bottom %}{% endblock bottom %}

{# 网页底部引用文件快 #}
{% block bottomfiles %} {% endblock bottomfiles %}

</body>
</html>

templates/base_deatil_list.html
{# 详情页， 列表页 #}
{% extends 'base.html' %}
{% if cart_count is not None %}
{% block cartCount %}{{ cart_count }}{% endblock cartCount %}
{% endif %}
{% block body %}
    <div class="navbar_con">
        <div class="navbar clearfix">
            <div class="subnav_con fl">
                <h1>全部商品分类</h1>
                <span></span>
                <ul class="subnav">
                    {% for type in types %}
                        <li><a href="{% url 'goods:list' type.id 1 %}" class="{{ type.logo }}">{{ type.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <ul class="navlist fl">
                <li><a href="{% url 'goods:index' %}">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="">抽奖</a></li>
            </ul>
        </div>
    </div>
    {# 主题内容 #}
    {% block main_content %}{% endblock main_content %}
{% endblock body %}

templates/base_nocart.html
{# 购物车， 用户中心， 提交订单 #}
{% extends 'base.html' %}
{% load static %}
{# 顶部搜索块 #}
{% block search_bar %}
    <div class="search_bar clearfix">
        <a href="/index" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
        <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{% block page_title %}{% endblock page_title %}</div>
        <div class="search_con fr">
            <form method="get" action="/search">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
        </div>
    </div>
{% endblock search_bar %}

templates/base_static.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load static %}
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 页面标题块 #}
    <title>{% block title %}{% endblock title %}</title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {# 网页顶部引用文件块 #}
    {% block topfiles %} {% endblock topfiles %}
</head>
<body>
{# 网页顶部欢迎信息块 #}
{% block header_con %}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到天天生鲜!</div>
            <div class="fr">
                <div class="login_btn fl">
                    <a href="{% url 'user:login' %}">登录</a>
                    <span>|</span>
                    <a href="{% url 'user:register' %}">注册</a>
                </div>
                <div class="user_link fl">
                    <span>|</span>
                    <a href="{% url 'user:user' %}">用户中心</a>
                    <span>|</span>
                    <a href="{% url 'cart:cart' %}">我的购物车</a>
                    <span>|</span>
                    <a href="{% url 'user:order' %}">我的订单</a>
                </div>
            </div>
        </div>
    </div>
{% endblock header_con %}

{# 顶部搜索块 #}
{% block search_bar %}
    <div class="search_bar clearfix">
        <a href="/index" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
        <div class="search_con fl">
            <input type="text" class="input_text fl" name="" placeholder="搜索商品">
            <input type="button" class="input_btn fr" name="" value="搜索">
        </div>
        <div class="guest_cart fr">
            <a href="/cart" class="cart_name fl">我的购物车</a>
            <div class="goods_count fl" id="show_count">0</div>
        </div>
    </div>
{% endblock search_bar %}

<body>
{# 主体 #}
{% block body %}{% endblock body %}
</body>

<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>
</div>

{# 网页底部html元素块 #}
{% block bottom %}{% endblock bottom %}

{# 网页底部引用文件快 #}
{% block bottomfiles %} {% endblock bottomfiles %}

</body>
</html>

templates/cart.html
{% extends 'base_nocart.html' %}
{% load static %}
{% block title %}天天生鲜-购物车{% endblock title %}
{% block page_title %}购物车{% endblock page_title %}
{% block body %}
	<div class="total_count">全部商品<em>2</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
    {% for sku in skus %}
	    <ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="" checked></li>
		<li class="col02"><img src="{{ sku.image.url }}"></li>
		<li class="col03">{{ sku.name }}<br><em>{{ sku.price }}元/{{ sku.unite }}</em></li>
		<li class="col04">{{ sku.unite }}</li>
		<li class="col05">{{ sku.price }}元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" class="num_show fl" value="{{ sku.count }}">
				<a href="javascript:;" class="minus fl">-</a>
			</div>
		</li>
		<li class="col07">{{ sku.amount }}</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>
    {% endfor %}
	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>{{ total_amount }}</em><br>共计<b>{{ total_count }}</b>件商品</li>
		<li class="col04"><a href="/order/place_order">去结算</a></li>
	</ul>
{% endblock body %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}天天生鲜-首页{% endblock title %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}
{% block cartCount %}{{ cart_count }}{% endblock cartCount %}
{% block body %}
    <div class="navbar_con">
        <div class="navbar">
            <h1 class="fl">全部商品分类</h1>
            <ul class="navlist fl">
                <li><a href="">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="">抽奖</a></li>
            </ul>
        </div>
    </div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for type in types %}
			    <li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
            {% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {% for banner in goods_banners %}
                    <li><a href="#"><img src="{{ banner.image.url }}" alt="幻灯片"></a></li>
                {% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
            {% for pbanner in promotion_banners %}
			    <a href="{{ pbanner.url }}"><img src="{{ pbanner.image.url }}"></a>
            {% endfor %}
		</div>
	</div>

    {% for type in types %}
	    <div class="list_model">
            <div class="list_title clearfix">
                <h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>
                <div class="subtitle fl">
                    <span>|</span>
                    {%  for banner in type.title_banners %}
                        <a href="#">{{ banner.sku.name }}</a>
                    {% endfor %}
                </div>
                <a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
            </div>

            <div class="goods_con clearfix">
                <div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
                <ul class="goods_list fl">
                    {%  for banner in type.image_banners %}
                    <li>
                        <h4><a href="#">{{ banner.sku.name }}</a></h4>
                        <a href="#"><img src="{{ banner.sku.image.url }}"></a>
                        <div class="prize">{{ banner.sku.price }}</div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% empty %}
        <div>
        </div>
    {% endfor %}

{% endblock body %}

templates/index_static.html
{% extends 'base_static.html' %}
{% load static %}
{% block title %}天天生鲜-首页{% endblock title %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}
{% block body %}
    <div class="navbar_con">
        <div class="navbar">
            <h1 class="fl">全部商品分类</h1>
            <ul class="navlist fl">
                <li><a href="">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="">抽奖</a></li>
            </ul>
        </div>
    </div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for type in types %}
			    <li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
            {% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {% for banner in goods_banners %}
                    <li><a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.image.url }}" alt="幻灯片"></a></li>
                {% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
            {% for pbanner in promotion_banners %}
			    <a href="{{ pbanner.url }}"><img src="{{ pbanner.image.url }}"></a>
            {% endfor %}
		</div>
	</div>

    {% for type in types %}
	    <div class="list_model">
            <div class="list_title clearfix">
                <h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>
                <div class="subtitle fl">
                    <span>|</span>
                    {%  for banner in type.title_banners %}
                        <a href="#">{{ banner.sku.name }}</a>
                    {% endfor %}
                </div>
                <a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
            </div>

            <div class="goods_con clearfix">
                <div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
                <ul class="goods_list fl">
                    {%  for banner in type.image_banners %}
                    <li>
                        <h4><a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a></h4>
                        <a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.sku.image.url }}"></a>
                        <div class="prize">{{ banner.sku.price }}</div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% empty %}
        <div>
        </div>
    {% endfor %}

{% endblock body %}

templates/list.html
{% extends 'base_deatil_list.html' %}
{% load static %}
{% block title %}天天生鲜-商品列表{% endblock title %}

{% block main_content %}
    <div class="breadcrumb">
        <a href="#">全部分类</a>
        <span>></span>
        <a href="#">{{ type.name }}</a>
    </div>
    <div class="main_wrap clearfix">
        <div class="l_wrap fl clearfix">
            <div class="new_goods">
                <h3>新品推荐</h3>
                <ul>
                    {% for new_sku in new_skus %}
                        <li>
                            <a href="{% url 'goods:detail' new_sku.id %}"><img src="{{ new_sku.image.url }}"></a>
                            <h4><a href="{% url 'goods:detail' new_sku.id %}">{{ new_sku.name }}</a></h4>
                            <div class="prize">￥{{ new_sku.price }}</div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <div class="r_wrap fr clearfix">
            <div class="sort_bar">
                 <a href="{% url 'goods:list' type.id 1 %}" {% if sort == 'default' %} class="active" {% endif %}>默认</a>
                <a href="{% url 'goods:list' type.id 1 %}?sort=price" {% if sort == 'price' %} class="active" {% endif %}>价格</a>
                <a href="{% url 'goods:list' type.id 1 %}?sort=sales" {% if sort == 'sales' %} class="active" {% endif %}>人气</a>
            </div>

            <ul class="goods_type_list clearfix">
                {% for sku in skus_page.object_list %}
                    <li>
                        <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
                        <h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ sku.price }}</span>
                            <span class="unit">{{ sku.unite }}</span>
                            <a href="#" class="add_goods" title="加入购物车"></a>
                        </div>
                    </li>
                {% endfor %}
            </ul>

            <div class="pagenation">
                {% if skus_page.has_previous %}
                    <a href="{% url 'goods:list' type.id skus_page.previous_page_number %}?sort={{ sort }}">
                        <上一页
                    </a>
                {% endif %}
{#                {% for pindex in skus_page.paginator.page_range %}#}
                {% for pindex in pages %}
                    {% if pindex == skus_page.number %}
                        <a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}" class="active">{{ pindex }}</a>
                    {% else %}
                        <a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}">{{ pindex }}</a>
                    {% endif %}
                {% endfor %}
                {% if skus_page.has_next %}
                    <a href="{% url 'goods:list' type.id skus_page.next_page_number %}?sort={{ sort }}">下一页></a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock main_content %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}天天生鲜-登录{% endblock title %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
    <div class="login_top clearfix">
		<a href="/" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/user/register">立即注册</a>
				</div>
				<div class="form_input">
{#                   不设置action时，会向浏览器栏中的地址提交请求 #}
					<form method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" value="{{ username }}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remember" {{ checked }}>
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
                    {{ errmsg }}
				</div>
			</div>
		</div>
	</div>
{% endblock body %}

templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}天天生鲜-注册{% endblock title %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
{% endblock topfiles %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
    <div class="register_con">
        <div class="l_con fl">
            <a href="/" class="reg_logo"><img src="{% static 'images/logo02.png'%}"></a>
            <div class="reg_slogan">足不出户  ·  新鲜每一天</div>
            <div class="reg_banner"></div>
        </div>

        <div class="r_con fr">
            <div class="reg_title clearfix">
                <h1>用户注册</h1>
                <a href="/user/login">登录</a>
            </div>
            <div class="reg_form clearfix">
                <form method="post" action="/user/register">
                    {% csrf_token %}
                <ul>
                    <li>
                        <label>用户名:</label>
                        <input type="text" name="user_name" id="user_name">
                        <span class="error_tip">提示信息</span>
                    </li>
                    <li>
                        <label>密码:</label>
                        <input type="password" name="pwd" id="pwd">
                        <span class="error_tip">提示信息</span>
                    </li>
                    <li>
                        <label>确认密码:</label>
                        <input type="password" name="cpwd" id="cpwd">
                        <span class="error_tip">提示信息</span>
                    </li>
                    <li>
                        <label>邮箱:</label>
                        <input type="text" name="email" id="email">
                        <span class="error_tip">提示信息</span>
                    </li>
                    <li class="agreement">
                        <input type="checkbox" name="allow" id="allow" checked="checked">
                        <label>同意”天天生鲜用户使用协议“</label>
                        <span class="error_tip2">提示信息</span>
                    </li>
                    <li class="reg_sub">
                        <input type="submit" value="注 册" name="">
                    </li>
                </ul>
                </form>
                {{ errmsg }}
            </div>
        </div>
    </div>
{% endblock body %}

templates/user_center_info.html
{% extends 'base_user_center.html' %}
{% load static %}
{% block right_content %}
    <div class="right_content clearfix">
        <div class="info_con clearfix">
        <h3 class="common_title2">基本信息</h3>
            <ul class="user_info_list">
                <li><span>用户名：</span>{{ user.username }}</li>
                {% if address %}
                        <li><span>联系方式：</span>{{ address.phone }}</li>
                        <li><span>联系地址：</span>{{ address.addr }}</li>
                    {% else %}
                        <li><span>联系方式：</span>无</li>
                        <li><span>联系地址：</span>无</li>
                    {% endif %}
                </ul>
        </div>

        <h3 class="common_title2">最近浏览</h3>
        <div class="has_view_list">
            <ul class="goods_type_list clearfix">
                {% for goods in goodsList %}
                    <li>
                        <a href="{% url 'goods:detail' goods.id %}"><img src="{{ goods.image.url }}"></a>
                        <h4><a href="{% url 'goods:detail' goods.id %}">{{ goods.name }}</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ goods.price }}</span>
                            <span class="unit">{{ goods.unite }}</span>
                            <a href="#" class="add_goods" title="加入购物车"></a>
                        </div>
                    </li>
                {% empty %}
                    <li>
                        <a>暂无历史记录</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock right_content %}

